### PR TITLE
add feature for viewing csv in html table

### PR DESCRIPTION
**Pull request by Stancobridge**
added feature to view csv content in html table and render it to document

### CODE REVIEW

**Comment by bacloud14** [comment]
oh you rock man !

**Comment by bacloud14** [comment]
Could you please limit to head of maximum 10 rows (if the file contains more..)?

**Comment by Stancobridge** [comment]
> Could you please limit to head of maximum 10 rows (if the file contains more..)?
Yeah, will do that too, I invited my friend to do the UI, he has submitted pull request but haven't been merged

**Comment by bacloud14** [comment]
Wonderful, you guys rock ! this help keeping me motivated to look for a graph visualization and push the tiny service forward;

**Comment by bacloud14** [comment]
I will give you both credit for sure for the last presentable result, that I will announce in my circles !

**Comment by Stancobridge** [comment]
okay thanks, seems am late, I the limit issue has been fixed, I wanted to push and notice some changes

**Comment by bacloud14** [comment]
yes I forgot to tell. many thanks anyway. Although I do not know if we should fix HTML or styling because if you saw, when I upload a little big file (~>200 rows) the HTML is messed up, I really only know Javascript and not HTML and CSS

**Comment by bacloud14** [comment]
by the way the styling of your friend is amazing ! many thanks to you both

**Pull request merged**
