### PR TITLE
Change in Ui and Processing Time And Other

### PR DESCRIPTION
**Pull request by akash2408**
1. Responsive UI
2. Increase File Processing Time to 2 min
3. User Now Only Can Upload .xls,.xlsx.,.txt files
4. Animated Process Bar
5. Nice Footer
6. Background Gradient

### CODE REVIEW

**Comment by bacloud14** [comment]
I very much like what you've done really ! this is a big plus, CSS is great, I am also very happy of JS improvements.
Could you please revise Adjacency Matrix plot ? I do not know what didn't go well.

**Comment by akash2408** [comment]
Yahhh sure,Iam looking at it

**Comment by bacloud14** [comment]
Also your starting point was I believe one commit behind, now it would be a little hard to update with your modifications (especially Linting JavaScript code), diff is hard to track. But no worries, the commit missed was for updating Dom after a file has been processed:

Commit: https://github.com/bacloud14/js_arules/commit/c990d4537d587cbe3729ce72d6174201cbba057d

Most code I believe was 

1. Reset dom

https://github.com/bacloud14/js_arules/blob/45cc0ae840fa9818214a628ef448a2fb5f28c282/js/app.js#L82
to
https://github.com/bacloud14/js_arules/blob/45cc0ae840fa9818214a628ef448a2fb5f28c282/js/app.js#L94

2. worker.terminate 

You can ignore or try to re update ...

**Comment by akash2408** [comment]
i will re update it no worry

**Pull request closed without merging**
