### PR TITLE
Change style of the whole page

### PR DESCRIPTION
**Pull request by JoseDeFreitas**
Hello! I'm creating this Pull request according to issue #17.
The style is more modern now. Colors are gray and white, with the addition of a nice purple 🎨.

## Changes made:
- Create CSS variables (so you just need to change them in one place.)
- Add default styles to classes. This allows adding a simple class to get a style (added only for items that are repeated.)
- Add Roboto and Nunito font. The font structure is: Roboto -> Nunito -> sans-serif.
- Responsive. The design looks good on desktop, tablet, and mobile screen sizes.
- Add comments to separate the content and make the code easier to read and find what you want.
- Change HTML tags to meet recommendations (for example, change "div" to "footer" tag.)
- Detele styles.css file, which was just holding very few styles that can be added instead in main.cc
- Delete default styling from W3.
- Take a screenshot of the new style and replace it with the old one (home.png.)

Let me know what you think about it. I can change whatever you want. If you find any issue with the layout or the responsiveness tell me. Hope you like it 👨‍🎨.

### CODE REVIEW

**Comment by bacloud14** [comment]
Hey @JoseDeFreitas , big work, but I would say Oups for now, your commit was a little behind, my merge was not correct I think, I am revising what I did wrong, because style is corrupt, 

It seemed you ported /js/style.css to css/style.css .?

**Comment by bacloud14** [comment]
Yes I confirm it is corrupt as I tested your exact version, if you fix it, just commit again, I would override prior 2 commits, as it was just centering sections (titles) and other minor modifications ..

thanks a lot

**Comment by bacloud14** [comment]
I cannot thank you enough, as this would be a big plus, really. 💯

**Comment by bacloud14** [comment]
Did you try importing this file as an example as well ?
https://www.stats.govt.nz/assets/Uploads/Environmental-economic-accounts/Environmental-economic-accounts-2020-tables/Download-data/renewable-energy-stock-account-2007-18.csv

**Comment by JoseDeFreitas** [comment]
@bacloud14 is there still a problem? I see you merged it. And thank you, I'm glad you liked it! 😄

**Comment by bacloud14** [comment]
I don't know what is wrong but yes layout is corrupt 100%

**Pull request merged**
